// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/citwild/wfe/store (interfaces: UsersStore)

package mockstore

import (
	"github.com/golang/mock/gomock"
)

// Mock of UsersStore interface
type MockUsersStore struct {
	ctrl     *gomock.Controller
	recorder *_MockUsersStoreRecorder
}

// Recorder for MockUsersStore (not exported)
type _MockUsersStoreRecorder struct {
	mock *MockUsersStore
}

func NewMockUsersStore(ctrl *gomock.Controller) *MockUsersStore {
	mock := &MockUsersStore{ctrl: ctrl}
	mock.recorder = &_MockUsersStoreRecorder{mock}
	return mock
}

func (_m *MockUsersStore) EXPECT() *_MockUsersStoreRecorder {
	return _m.recorder
}
