// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/citwild/wfe/stores (interfaces: AccountsStore)

package mockstores

import (
	"github.com/citwild/wfe/api"
	"github.com/golang/mock/gomock"
	"golang.org/x/net/context"
)

// Mock of AccountsStore interface
type MockAccountsStore struct {
	ctrl     *gomock.Controller
	recorder *_MockAccountsStoreRecorder
}

// Recorder for MockAccountsStore (not exported)
type _MockAccountsStoreRecorder struct {
	mock *MockAccountsStore
}

func NewMockAccountsStore(ctrl *gomock.Controller) *MockAccountsStore {
	mock := &MockAccountsStore{ctrl: ctrl}
	mock.recorder = &_MockAccountsStoreRecorder{mock}
	return mock
}

func (_m *MockAccountsStore) EXPECT() *_MockAccountsStoreRecorder {
	return _m.recorder
}

func (_m *MockAccountsStore) Create(_param0 context.Context, _param1 *api.User, _param2 *api.EmailAddress) (*api.User, error) {
	ret := _m.ctrl.Call(_m, "Create", _param0, _param1, _param2)
	ret0, _ := ret[0].(*api.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAccountsStoreRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Create", arg0, arg1, arg2)
}
