// Code generated by protoc-gen-go.
// source: accounts.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	accounts.proto

It has these top-level messages:
	User
	EmailAddress
	CreatedAccount
	NewAccount
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UID   int32  `protobuf:"varint,1,opt,name=UID,json=uID" json:"UID,omitempty"`
	Login string `protobuf:"bytes,2,opt,name=Login,json=login" json:"Login,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=Name,json=name" json:"Name,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EmailAddress struct {
	Email string `protobuf:"bytes,1,opt,name=Email,json=email" json:"Email,omitempty"`
}

func (m *EmailAddress) Reset()                    { *m = EmailAddress{} }
func (m *EmailAddress) String() string            { return proto.CompactTextString(m) }
func (*EmailAddress) ProtoMessage()               {}
func (*EmailAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreatedAccount struct {
	UID int32 `protobuf:"varint,1,opt,name=UID,json=uID" json:"UID,omitempty"`
}

func (m *CreatedAccount) Reset()                    { *m = CreatedAccount{} }
func (m *CreatedAccount) String() string            { return proto.CompactTextString(m) }
func (*CreatedAccount) ProtoMessage()               {}
func (*CreatedAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type NewAccount struct {
	UID      int32  `protobuf:"varint,1,opt,name=UID,json=uID" json:"UID,omitempty"`
	Login    string `protobuf:"bytes,2,opt,name=Login,json=login" json:"Login,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=Email,json=email" json:"Email,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *NewAccount) Reset()                    { *m = NewAccount{} }
func (m *NewAccount) String() string            { return proto.CompactTextString(m) }
func (*NewAccount) ProtoMessage()               {}
func (*NewAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*EmailAddress)(nil), "api.EmailAddress")
	proto.RegisterType((*CreatedAccount)(nil), "api.CreatedAccount")
	proto.RegisterType((*NewAccount)(nil), "api.NewAccount")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Accounts service

type AccountsClient interface {
	Create(ctx context.Context, in *NewAccount, opts ...grpc.CallOption) (*CreatedAccount, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) Create(ctx context.Context, in *NewAccount, opts ...grpc.CallOption) (*CreatedAccount, error) {
	out := new(CreatedAccount)
	err := grpc.Invoke(ctx, "/api.Accounts/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Accounts service

type AccountsServer interface {
	Create(context.Context, *NewAccount) (*CreatedAccount, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Accounts/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Create(ctx, req.(*NewAccount))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Accounts_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54,
	0x72, 0xe2, 0x62, 0x09, 0x2d, 0x4e, 0x2d, 0x12, 0x12, 0xe0, 0x62, 0x0e, 0xf5, 0x74, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0x2e, 0xf5, 0x74, 0x11, 0x12, 0xe1, 0x62, 0xf5, 0xc9, 0x4f,
	0xcf, 0xcc, 0x93, 0x60, 0x02, 0x8a, 0x71, 0x06, 0xb1, 0xe6, 0x80, 0x38, 0x42, 0x42, 0x5c, 0x2c,
	0x7e, 0x89, 0xb9, 0xa9, 0x12, 0xcc, 0x60, 0x41, 0x96, 0x3c, 0x20, 0x5b, 0x49, 0x85, 0x8b, 0xc7,
	0x35, 0x37, 0x31, 0x33, 0xc7, 0x31, 0x25, 0xa5, 0x28, 0xb5, 0xb8, 0x18, 0xa4, 0x13, 0xcc, 0x07,
	0x9b, 0x06, 0xd4, 0x99, 0x0a, 0xe2, 0x28, 0x29, 0x71, 0xf1, 0x39, 0x17, 0xa5, 0x26, 0x96, 0xa4,
	0xa6, 0x38, 0x42, 0xdc, 0x81, 0x69, 0xa7, 0x52, 0x1a, 0x17, 0x97, 0x5f, 0x6a, 0x39, 0x4e, 0x79,
	0x1c, 0x6e, 0x82, 0xdb, 0xc7, 0x8c, 0x64, 0x9f, 0x90, 0x14, 0x17, 0x47, 0x40, 0x62, 0x71, 0x71,
	0x79, 0x7e, 0x51, 0x8a, 0x04, 0x0b, 0x58, 0x82, 0xa3, 0x00, 0xca, 0x37, 0xb2, 0xe2, 0xe2, 0x80,
	0x5a, 0x52, 0x2c, 0xa4, 0xc7, 0xc5, 0x06, 0x71, 0x97, 0x10, 0xbf, 0x1e, 0x30, 0x44, 0xf4, 0x10,
	0x0e, 0x90, 0x12, 0x06, 0x0b, 0xa0, 0xba, 0x3a, 0x89, 0x0d, 0x1c, 0x7a, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xed, 0x44, 0x27, 0x03, 0x4f, 0x01, 0x00, 0x00,
}
