// Code generated by protoc-gen-go.
// source: accounts.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	accounts.proto
	users.proto

It has these top-level messages:
	EmailAddress
	CreatedAccount
	NewAccount
	User
	UserSpec
*/
package api

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

import (
	"golang.org/x/net/context"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailAddress struct {
	Email string `protobuf:"bytes,1,opt,name=Email,json=email" json:"Email,omitempty"`
}

func (m *EmailAddress) Reset()                    { *m = EmailAddress{} }
func (m *EmailAddress) String() string            { return proto.CompactTextString(m) }
func (*EmailAddress) ProtoMessage()               {}
func (*EmailAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreatedAccount struct {
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *CreatedAccount) Reset()                    { *m = CreatedAccount{} }
func (m *CreatedAccount) String() string            { return proto.CompactTextString(m) }
func (*CreatedAccount) ProtoMessage()               {}
func (*CreatedAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NewAccount struct {
	Login    string `protobuf:"bytes,1,opt,name=Login,json=login" json:"Login,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=Email,json=email" json:"Email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *NewAccount) Reset()                    { *m = NewAccount{} }
func (m *NewAccount) String() string            { return proto.CompactTextString(m) }
func (*NewAccount) ProtoMessage()               {}
func (*NewAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*EmailAddress)(nil), "api.EmailAddress")
	proto.RegisterType((*CreatedAccount)(nil), "api.CreatedAccount")
	proto.RegisterType((*NewAccount)(nil), "api.NewAccount")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Accounts service

type AccountsClient interface {
	Create(ctx context.Context, in *NewAccount, opts ...grpc.CallOption) (*CreatedAccount, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) Create(ctx context.Context, in *NewAccount, opts ...grpc.CallOption) (*CreatedAccount, error) {
	out := new(CreatedAccount)
	err := grpc.Invoke(ctx, "/api.Accounts/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Accounts service

type AccountsServer interface {
	Create(context.Context, *NewAccount) (*CreatedAccount, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Accounts/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Create(ctx, req.(*NewAccount))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Accounts_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54,
	0x52, 0xe1, 0xe2, 0x71, 0xcd, 0x4d, 0xcc, 0xcc, 0x71, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x16,
	0x12, 0xe1, 0x62, 0x05, 0xf3, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x58, 0x53, 0x41, 0x1c,
	0x25, 0x05, 0x2e, 0x3e, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0x14, 0x47, 0x88, 0x19, 0x42, 0x7c,
	0x5c, 0x4c, 0x9e, 0x2e, 0x50, 0x45, 0x4c, 0x99, 0x2e, 0x4a, 0x21, 0x5c, 0x5c, 0x7e, 0xa9, 0xe5,
	0x30, 0x59, 0xa0, 0x29, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0x30, 0x53, 0x72, 0x40, 0x1c, 0x84, 0xd9,
	0x4c, 0x48, 0x66, 0x0b, 0x49, 0x71, 0x71, 0x04, 0x24, 0x16, 0x17, 0x97, 0xe7, 0x17, 0xa5, 0x48,
	0x30, 0x83, 0x25, 0x38, 0x0a, 0xa0, 0x7c, 0x23, 0x2b, 0x2e, 0x0e, 0xa8, 0x91, 0xc5, 0x42, 0x7a,
	0x5c, 0x6c, 0x10, 0x37, 0x08, 0xf1, 0xeb, 0x01, 0x5d, 0xae, 0x87, 0xb0, 0x4e, 0x4a, 0x18, 0x2c,
	0x80, 0xea, 0xc2, 0x24, 0x36, 0xb0, 0x2f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x79, 0xbb,
	0xf1, 0x3f, 0xf7, 0x00, 0x00, 0x00,
}
