// Code generated by protoc-gen-gogo.
// source: wfe.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	wfe.proto

It has these top-level messages:
	User
	CreatedAccount
	NewAccount
	Empty
*/
package api

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion1

type User struct {
	UID   int32  `protobuf:"varint,1,opt,name=UID,json=uID,proto3" json:"UID,omitempty"`
	Login string `protobuf:"bytes,2,opt,name=Login,json=login,proto3" json:"Login,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptorWfe, []int{0} }

type CreatedAccount struct {
	UID int32 `protobuf:"varint,1,opt,name=UID,json=uID,proto3" json:"UID,omitempty"`
}

func (m *CreatedAccount) Reset()                    { *m = CreatedAccount{} }
func (m *CreatedAccount) String() string            { return proto.CompactTextString(m) }
func (*CreatedAccount) ProtoMessage()               {}
func (*CreatedAccount) Descriptor() ([]byte, []int) { return fileDescriptorWfe, []int{1} }

type NewAccount struct {
	Login    string `protobuf:"bytes,1,opt,name=Login,json=login,proto3" json:"Login,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	UID      int32  `protobuf:"varint,4,opt,name=UID,json=uID,proto3" json:"UID,omitempty"`
}

func (m *NewAccount) Reset()                    { *m = NewAccount{} }
func (m *NewAccount) String() string            { return proto.CompactTextString(m) }
func (*NewAccount) ProtoMessage()               {}
func (*NewAccount) Descriptor() ([]byte, []int) { return fileDescriptorWfe, []int{2} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptorWfe, []int{3} }

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*CreatedAccount)(nil), "api.CreatedAccount")
	proto.RegisterType((*NewAccount)(nil), "api.NewAccount")
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Accounts service

type AccountsClient interface {
	Create(ctx context.Context, in *NewAccount, opts ...grpc.CallOption) (*CreatedAccount, error)
	Update(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) Create(ctx context.Context, in *NewAccount, opts ...grpc.CallOption) (*CreatedAccount, error) {
	out := new(CreatedAccount)
	err := grpc.Invoke(ctx, "/api.Accounts/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Update(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/api.Accounts/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Accounts service

type AccountsServer interface {
	Create(context.Context, *NewAccount) (*CreatedAccount, error)
	Update(context.Context, *User) (*Empty, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Accounts/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Create(ctx, req.(*NewAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Accounts/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Update(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Accounts_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Accounts_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptorWfe,
}

var fileDescriptorWfe = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4f, 0x4b, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x72, 0xe2, 0x62, 0x09, 0x2d,
	0x4e, 0x2d, 0x12, 0x12, 0xe0, 0x62, 0x0e, 0xf5, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d,
	0x62, 0x2e, 0xf5, 0x74, 0x11, 0x12, 0xe1, 0x62, 0xf5, 0xc9, 0x4f, 0xcf, 0xcc, 0x93, 0x60, 0x02,
	0x8a, 0x71, 0x06, 0xb1, 0xe6, 0x80, 0x38, 0x42, 0x42, 0x5c, 0x2c, 0x7e, 0x89, 0xb9, 0xa9, 0x12,
	0xcc, 0x60, 0x41, 0x96, 0x3c, 0x20, 0x5b, 0x49, 0x89, 0x8b, 0xcf, 0xb9, 0x28, 0x35, 0xb1, 0x24,
	0x35, 0xc5, 0x31, 0x39, 0x39, 0xbf, 0x34, 0xaf, 0x04, 0xd3, 0x34, 0xa5, 0x34, 0x2e, 0x2e, 0xbf,
	0xd4, 0x72, 0x98, 0x3c, 0xdc, 0x6c, 0x46, 0x64, 0xb3, 0x81, 0xa2, 0xae, 0xb9, 0x89, 0x99, 0x39,
	0x30, 0x1b, 0x53, 0x41, 0x1c, 0x21, 0x29, 0x2e, 0x8e, 0x80, 0xc4, 0xe2, 0xe2, 0xf2, 0xfc, 0xa2,
	0x14, 0xa8, 0xad, 0x1c, 0x05, 0x50, 0x3e, 0xcc, 0x1e, 0x16, 0x84, 0x3d, 0xec, 0x20, 0x33, 0x0a,
	0x4a, 0x2a, 0x8d, 0xa2, 0xb9, 0x38, 0xa0, 0xb6, 0x15, 0x0b, 0xe9, 0x71, 0xb1, 0x41, 0x1c, 0x28,
	0xc4, 0xaf, 0x07, 0xf4, 0xb4, 0x1e, 0xc2, 0x25, 0x52, 0xc2, 0x60, 0x01, 0x34, 0xe7, 0xcb, 0x73,
	0xb1, 0x85, 0x16, 0xa4, 0x80, 0xd4, 0x73, 0x82, 0xa5, 0x41, 0x21, 0x24, 0xc5, 0x05, 0x66, 0x82,
	0x0d, 0x4f, 0x62, 0x03, 0x87, 0xa0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x25, 0x52, 0xb0, 0xaa,
	0x4e, 0x01, 0x00, 0x00,
}
